### ISSUE TITLE
get_gambl_metadata relies on files that aren't in the repo

### ISSUE THREAD

**Issue by rdmorin** [morinlab/GAMBLR#127]
Some of the sample sets that can be accessed with get_gambl_metadata cause the function to break if run off-site. This is because files it's using do not exist in the repo or the path is specified wrong. For example:

```
get_gambl_metadata(case_set="BL-DLBCL-manuscript")
Error in data.table::fread("/projects/rmorin/projects/gambl-repos/gambl-kdreval/data/metadata/BLGSP--DLBCL-case-set.tsv") :                                                                               
  File '/projects/rmorin/projects/gambl-repos/gambl-kdreval/data/metadata/BLGSP--DLBCL-case-set.tsv' does not exist or is non-readable. getwd()=='/Users/rmorin/git/GAMBLR'
```

All files that GAMBLR loads must be either in the gambl repo (with the path specified properly using the relative path and config) or, in rare cases, bundled with GAMBLR.

**Comment by Kdreval** [comment]
This file is on master, e.g.: https://github.com/morinlab/gambl/blob/master/data/metadata/BLGSP--DLBCL-case-set.tsv
I think what is missing is that `get_gambl_metadata()` should use the `config::get()` and construct the path to this (and other) files like we do in other functions rather than have it hardcoded. Similar would need to be done also for case sets `BL-DLBCL-manuscript-HTMCP` and `FL-DLBCL-all`.
I am working on update to other GAMBLR functions, and can fix this bug there
