### ISSUE TITLE
Examples (vignettes and package docs) using bundled data that has been relocated to GAMBLR.data now fails

### ISSUE THREAD

**Issue by mattssca** [morinlab/GAMBLR#200]
Examples in the vignettes that are reading bundled GAMBLR data, that has now been relocated to their own dedicated repo need to be updated.

For instance;
```
Error: processing vignette 'ssm_tutorial.Rmd' failed with diagnostics:
   object 'grch37_ashm_regions' not found
``` 

In addition, examples in the package documentation that are calling any of the relocated datasets also need to be updated.

**Comment by Kdreval** [comment]
I did some exploration on this and it looks like this is happening because these new objects are not exported. Adding the `@export` tag fixes this issue but I think the bigger problem is that the `load_all()` acts differently from `install()` and when the package is installed, only the version of the bundled data specified in config during the installation step is returned and cannot be changed then, which is different from the `load_all()` step and is not what we want.

**Comment by mattssca** [comment]
I proposed a potential fix for this issue in the most recent commit on my [PR](https://github.com/morinlab/GAMBLR/pull/196).

**Comment by rdmorin** [comment]
Which commit had the potential fix?

**Comment by mattssca** [comment]
[This](https://github.com/morinlab/GAMBLR/pull/196/commits/1dcca3273d2f89ec5c05e0f16bd7d49b8f296338) commit.
