### ISSUE TITLE
Still finding references to `grch37_ashm_regions` throughout

### ISSUE THREAD

**Issue by lkhilton** [morinlab/GAMBLR#219]
With the migration of a bunch of data to `GAMBLR.data`, functions that call `{genome_build}_ashm_regions` are now referencing a nonexistent object. Is the best solution to give the aSHM data in `GAMBLR.data` an additional alias for backwards compatibility?

**Comment by Kdreval** [comment]
I think the designated data package is not working as efficiently as expected and this is another hidden issue that comes up and maybe to solve this the best approach is to roll back what we had before.

**Comment by rdmorin** [comment]
Is it just because the auto-loaded objects have a different name?

**Comment by Kdreval** [comment]
No this particular issues is because they are not having the @export and need to refer by `GAMBLR.data:::` but I think the bigger problem with that package is that it is not giving us the outcome we were hoping for (dynamically using a particular version of the dataset) and in addition to that creates lots of hidden issues like this that need changes to the existing code base

**Comment by rdmorin** [comment]
We fixed this, didn't we, Kostia?

**Comment by Kdreval** [comment]
Adam can you please confirm the fix works for you too if you update the package and call `library(GAMBLR.data)`? We can close this issue then if the fix works for you.
